# Generated by Django 2.2.5 on 2019-09-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20190910_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
