# Generated by Django 2.2.5 on 2019-09-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_auto_20190910_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basics',
            name='city',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='postalcode',
        ),
    ]
