# Generated by Django 2.2.5 on 2019-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_auto_20190911_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FilePathField(default=None, path='/home/vicky/Documents/doodle/Zoho-Cliqtrix/media'),
        ),
    ]
