# Generated by Django 2.2.5 on 2019-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FilePathField(null=True, path='/home/vicky/Documents/doodle/Zoho-Cliqtrix/media'),
        ),
    ]
