# Generated by Django 2.2.5 on 2019-09-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_auto_20190912_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
    ]
