# Generated by Django 2.2.5 on 2019-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0012_remove_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
